import type { MasterLocation } from '../../profile/model/masterLocation';

export const DEMO_MASTER_LOCATIONS: Record<string, MasterLocation> = {
  'demo-anna-smirnova': {
    visitType: 'studio',
    street: 'ул. Немига',
    building: '5',
    entrance: 'вход со стороны парковки',
    floor: '3 этаж',
    room: 'кабинет 312',
    intercom: 'Домофон 12, сказать на ресепшене SLOTTY',
    landmark: 'рядом с кофейней',
    directions:
      'Зайдите в главный вход, поднимитесь на 3 этаж и поверните направо. Кабинет будет в конце коридора.',
    clientNote: 'Приходите за 5 минут до записи',
    lat: 53.9038,
    lng: 27.5552,
  },
  'demo-igor-volkov': {
    visitType: 'studio',
    city: 'Минск',
    street: 'ул. Октябрьская',
    building: '16',
    entrance: 'главный вход',
    floor: '1 этаж',
    room: 'Barber Loft',
    landmark: 'возле красного кирпичного здания',
    directions: 'После входа идите прямо до ресепшена.',
    clientNote: 'Приходите за 5 минут до записи',
    lat: 53.8903,
    lng: 27.5559,
  },
  'demo-maria-lebedeva': {
    visitType: 'studio',
    street: 'пр-т Независимости',
    building: '168',
    entrance: 'вход через салон красоты',
    floor: '2 этаж',
    room: 'кабинет 204',
    landmark: 'рядом со станцией метро Уручье',
    directions: 'На ресепшене скажите, что вы к мастеру по бровям.',
    clientNote: 'Приходите за 5 минут до записи',
    lat: 53.9389,
    lng: 27.6895,
  },
  'demo-bodyform': {
    visitType: 'studio',
    street: 'ул. Грушевская',
    building: '8',
    entrance: 'отдельный вход с торца здания',
    floor: 'цоколь',
    room: 'зал BodyForm',
    landmark: 'район Малиновка, остановка «Грушевская»',
    directions: 'Спуститесь по лестнице слева от входа в ТЦ.',
    lat: 53.859,
    lng: 27.517,
  },
  'demo-massage-pro': {
    visitType: 'studio',
    street: 'пр-т Независимости',
    building: '95',
    entrance: 'парадный вход',
    floor: '4 этаж',
    room: 'офис 402',
    landmark: 'Центр, возле площади Независимости',
    directions: 'Лифт до 4 этажа, направо от лифта.',
    lat: 53.898,
    lng: 27.563,
  },
  'demo-tattoo-room': {
    visitType: 'studio',
    street: 'ул. Кирова',
    building: '3',
    entrance: 'вход со двора',
    floor: '2 этаж',
    room: 'студия Tattoo Room',
    landmark: 'Площадь Победы, 5 мин пешком',
    directions: 'Домофон 3, позвонить — вам откроют.',
    lat: 53.909,
    lng: 27.545,
  },
};

export function getDemoMasterLocation(masterId: string): MasterLocation | undefined {
  return DEMO_MASTER_LOCATIONS[masterId];
}
