/** Static assets under `public/photos/` — English paths only. */

export const PHOTO_ROOT = '/photos';

export const photo = (relativePath: string): string =>
  `${PHOTO_ROOT}/${relativePath.replace(/^\/+/, '')}`;

export const PHOTOS = {
  brand: {
    logo: photo('logo.webp'),
    logoHeader: photo('logo-header.webp'),
    hero: photo('hero.webp'),
    fon: photo('fon.webp'),
    nothingFound: photo('nothing-found.webp'),
  },
  landing: {
    dir: photo('landing'),
    background: photo('landing/background.webp'),
    master: photo('landing/master.webp'),
    masterFirst: photo('landing/master-first.webp'),
    line: photo('landing/line.webp'),
    bepaid: photo('landing/bepaid.webp'),
    tivonix: photo('landing/tivonix.webp'),
    green: photo('landing/green.webp'),
    blue: photo('landing/blue.webp'),
    red: photo('landing/red.webp'),
    bottom: photo('landing/bottom.webp'),
    slotty: photo('landing/slotty.webp'),
    catalog: (file: string) => photo(`landing/catalog/${file}`),
    servicesShowcase: (file: string) => photo(`landing/services-showcase/${file}`),
  },
  history: {
    dir: photo('history'),
    kpi1: photo('history/1.webp'),
    kpi2: photo('history/2.webp'),
    kpi3: photo('history/3.webp'),
    green: photo('history/green.webp'),
    red: photo('history/red.webp'),
    redBlue: photo('history/red-blue.webp'),
    noSlots: photo('history/no-slots.webp'),
    filters: photo('history/filters.webp'),
  },
  awards: {
    topWeek: photo('awards/top-week.webp'),
    topMonth: photo('awards/top-month.webp'),
    starRating: photo('awards/star-rating.webp'),
    manyReviews: photo('awards/many-reviews.webp'),
    recentlyJoined: photo('awards/recently-joined.webp'),
    noAchievements: photo('awards/no-achievements.webp'),
  },
  badges: {
    check: photo('badges/check.webp'),
    cancel: photo('badges/cancel.webp'),
    warning: photo('badges/warning.webp'),
  },
  catalogServices: photo('catalog-services'),
  categories: (n: 1 | 2 | 3 | 4) => photo(`categories/${n}.webp`),
  plan: {
    dir: photo('plan'),
    manicure: photo('plan/manicure.webp'),
    barber: photo('plan/barber.webp'),
    brows: photo('plan/brows.webp'),
    massage: photo('plan/massage.webp'),
    fitness: photo('plan/fitness.webp'),
    tattoo: photo('plan/tattoo.webp'),
  },
  work: {
    manicure: photo('work/manicure.webp'),
    barbers: photo('work/barbers.webp'),
    browsLashes: photo('work/brows_lashes.webp'),
    massage: photo('work/massage.webp'),
    fitness: photo('work/fitness.webp'),
    tattoo: photo('work/tattoo.webp'),
  },
  howItWorks: (file: string) => photo(`how-it-works/${file}`),
  whySlotty: (file: string) => photo(`why-slotty/${file}`),
  scheduleTabs: (file: string) => photo(`schedule-tabs/${file}`),
  servicesTabs: (file: string) => photo(`services-tabs/${file}`),
  summary: (file: string) => photo(`summary/${file}`),
  quickSetup: {
    heroBg: photo('quick-setup/hero-bg.webp'),
    slide: (n: 1 | 2 | 3 | 4) => photo(`quick-setup/${n}.webp`),
  },
  legal: {
    refund: photo('refund/1.webp'),
    privacy: photo('privacy/1.webp'),
    contract: photo('contract/1.webp'),
    documentsBack: photo('documents/back.webp'),
  },
  cabinet: {
    visitComplete: photo('visit-complete/1.webp'),
    review: photo('review/1.webp'),
    deleteAccount: photo('delete-account/1.webp'),
    noRequests: photo('no-requests-found/empty.webp'),
    urgentHelp: photo('urgent-help/1.webp'),
    status: photo('status/1.webp'),
    proBadge: photo('pro/badge.webp'),
    barbershop: photo('barbershop/fon.webp'),
  },
  podium: (place: 1 | 2 | 3) => photo(`podium/${place}.webp`),
  login: (n: number) => photo(`login/${n}.webp`),
  notFound: photo('404/1.webp'),
  xtr: photo('xtr/1.webp'),
} as const;
